### ISSUE TITLE
Erro in back-projection package

### ISSUE THREAD

**Issue by gwsmelo** [iris-edu/backprojection#1]
Some errors are showing when I try running the example informed on INSTALL file,
(base) local-admin@COS-GE-E056550 src % python3 back_projection_r2.py                                                   

Error processing line 1 of /Users/local-admin/opt/anaconda3/lib/python3.9/site-packages/matplotlib-nspkg.pth:

  Traceback (most recent call last):

    File "/Users/local-admin/opt/anaconda3/lib/python3.9/site.py", line 169, in addpackage

      exec(line)

    File "<string>", line 1, in <module>

    File "<frozen importlib._bootstrap>", line 562, in module_from_spec

  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored

Traceback (most recent call last):

  File "/Users/local-admin/analyse_back-projection/backprojection-main/src/back_projection_r2.py", line 4, in <module>

    from mpl_toolkits.basemap import Basemap

ModuleNotFoundError: No module named 'mpl_toolkits.basemap'

(base) local-admin@COS-GE-E056550 src % 

all packages necessary as said in INSTALL file (basemap              (tested with version 1.2.2)
             . obspy                (tested with version 1.2.2)
             . ffmpeg               (tested with version 4.4.1)
             . basemap-data-hires)

are already installed on my laptop. Also, INSTALL file shows,

 CONFIGURE THE PACKAGE:

        With Python configured, you should be able to run the package examples without further modifications. However:
        - if necessary, update the Python path on the first line of the src/aftershock_fdsn_maps.py

however, there is not any aftershock_fdsn_maps.py file inside the src folder. The single file contained is the back-projection_r2.py.

**Comment by manoch-iris** [comment]
Hi @gwsmelo,
The error you have received is due to issues with the required basemap module installation. We have tested and verified that the BackProjection package works as designed. To facilitate the installation of the required modules, we now have added a Python requirements file that contains a list of the required modules and packages. Please read and follow the installation procedure outline in the README file. This should ensure a uniform Python installation and a successful package execution.
